---
# tasks file for ansible-role-poudriere

- include_vars: "{{ ansible_os_family }}.yml"

- include: install-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- name: Create poudriere.conf
  template:
    src: poudriere.conf.j2
    dest: "{{ poudriere_conf }}"

# - name: Start poudriere
#   service:
#     name: "{{ poudriere_service }}"
#     enabled: true
#     state: started
